// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lerank-hero/AccessibilityFocused.tsx": () => import("../components/mockups/lerank-hero/AccessibilityFocused.tsx"),
  "./components/mockups/lerank-hero/AffordanceFirst.tsx": () => import("../components/mockups/lerank-hero/AffordanceFirst.tsx"),
  "./components/mockups/lerank-hero/InfoHierarchy.tsx": () => import("../components/mockups/lerank-hero/InfoHierarchy.tsx")
};
